#!/usr/bin/env python3
"""gen_index.py — Scan nightly report directories and generate index.html."""

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path


_CSS = """
:root{--green:#22c55e;--yellow:#f59e0b;--red:#ef4444;--blue:#3b82f6;
      --bg:#f9fafb;--card:#fff;--border:#e5e7eb;--text:#111827;--muted:#6b7280}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:system-ui,sans-serif;background:var(--bg);color:var(--text);padding:1.5rem;max-width:960px;margin:0 auto}
h1{font-size:1.5rem;font-weight:700;margin-bottom:.25rem}
.meta{color:var(--muted);font-size:.82rem;margin-bottom:1.5rem}
table{width:100%;border-collapse:collapse;font-size:.85rem}
th{background:#f3f4f6;text-align:left;padding:.5rem .75rem;border:1px solid var(--border);font-weight:600}
td{padding:.45rem .75rem;border:1px solid var(--border);vertical-align:middle}
tr:nth-child(even){background:#fafafa}
tr:hover{background:#f0f9ff}
.badge{display:inline-block;padding:.15rem .5rem;border-radius:.25rem;font-size:.75rem;font-weight:600}
.pass{background:#dcfce7;color:#166534}.fail{background:#fee2e2;color:#991b1b}
.partial{background:#fef3c7;color:#92400e}.unknown{background:#f3f4f6;color:#374151}
a{color:var(--blue);text-decoration:none}a:hover{text-decoration:underline}
.prog-wrap{background:#e5e7eb;border-radius:9999px;height:.6rem;width:120px;overflow:hidden;display:inline-block;vertical-align:middle}
.prog-bar{height:100%;border-radius:9999px;background:var(--green)}
"""


def _esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def parse_date(dirname: str) -> datetime | None:
    """Parse YYYYMMDD_HHMMSS directory name to datetime."""
    m = re.match(r"(\d{4})(\d{2})(\d{2})_(\d{2})(\d{2})(\d{2})", dirname)
    if not m:
        return None
    y, mo, d, h, mi, s = (int(x) for x in m.groups())
    return datetime(y, mo, d, h, mi, s, tzinfo=timezone.utc)


def load_summary(report_dir: Path) -> dict:
    """Extract summary data from a report directory."""
    summary: dict = {}

    # Read summary.json (generated by generate_report.py from registry)
    summ_path = report_dir / "summary.json"
    if summ_path.exists():
        try:
            prog = json.loads(summ_path.read_text())
            total = prog.get("total_ops", 0)
            done  = prog.get("done_ops", 0)
            summary["done_ops"]  = done
            summary["total_ops"] = total
            summary["pct"]       = done / total * 100 if total else 0
            # Derive test counts from categories
            tests_passed = prog.get("tested_ops", 0)
            total_ops = prog.get("total_ops", 0)
            summary["tests_total"]  = total_ops
            summary["tests_passed"] = tests_passed
            summary["tests_failed"] = total_ops - tests_passed
        except Exception:
            pass

    # Fallback: try test_results.xml for pass/fail counts (if summary.json not available)
    if "tests_total" not in summary:
        xml_path = report_dir / "test_results.xml"
        if xml_path.exists():
            try:
                import xml.etree.ElementTree as ET
                root = ET.parse(xml_path).getroot()
                suites = list(root) if root.tag == "testsuites" else [root]
                total = errors = failures = skipped = 0
                for s in suites:
                    total    += int(s.get("tests",    0))
                    errors   += int(s.get("errors",   0))
                    failures += int(s.get("failures", 0))
                    skipped  += int(s.get("skipped",  0))
                summary["tests_total"]  = total
                summary["tests_passed"] = total - errors - failures - skipped
                summary["tests_failed"] = failures + errors
            except Exception:
                pass

    return summary


def build_index(nightly_dir: Path, repo_url: str) -> str:
    """Scan nightly_dir for dated subdirectories and build index.html."""
    entries = []
    for d in nightly_dir.iterdir():
        if not d.is_dir():
            continue
        dt = parse_date(d.name)
        if dt is None:
            continue
        report_html = d / "report.html"
        if not report_html.exists():
            continue
        summary = load_summary(d)
        entries.append((dt, d.name, summary))

    entries.sort(key=lambda x: x[0], reverse=True)

    gen_time = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    rows = []
    for dt, dirname, s in entries:
        date_str = dt.strftime("%Y-%m-%d %H:%M UTC")
        link = f'<a href="{dirname}/report.html">{date_str}</a>'

        # Test badge
        if "tests_total" in s and s["tests_total"] > 0:
            f = s["tests_failed"]
            p = s["tests_passed"]
            cls = "pass" if f == 0 else "fail"
            test_cell = f'<span class="badge {cls}">{p} / {s["tests_total"]}</span>'
        else:
            test_cell = '<span class="badge unknown">—</span>'

        # Progress bar
        if "pct" in s:
            pct = s["pct"]
            prog_cell = (
                f'<div class="prog-wrap"><div class="prog-bar" style="width:{pct:.1f}%"></div></div>'
                f' <span style="font-size:.8rem;color:var(--muted)">'
                f'{s["done_ops"]}/{s["total_ops"]} ({pct:.0f}%)</span>'
            )
        else:
            prog_cell = '<span style="color:var(--muted)">—</span>'

        rows.append(f"<tr><td>{link}</td><td>{test_cell}</td><td>{prog_cell}</td></tr>")

    rows_html = "\n".join(rows) if rows else '<tr><td colspan="3">No reports yet.</td></tr>'

    return f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>TileOPs Nightly Reports</title>
<style>{_CSS}</style>
</head><body>
<h1>TileOPs Nightly Reports</h1>
<p class="meta">
  Source: <a href="{_esc(repo_url)}">{_esc(repo_url)}</a>
  &nbsp;·&nbsp; Updated: {gen_time}
</p>
<table>
<thead><tr><th>Run date (UTC)</th><th>Tests (pass / total)</th><th>Op progress</th></tr></thead>
<tbody>
{rows_html}
</tbody>
</table>
</body></html>
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate nightly report index.html")
    parser.add_argument("--nightly-dir", required=True, help="Directory containing dated report subdirs")
    parser.add_argument("--output",      required=True, help="Output index.html path")
    parser.add_argument("--repo-url",    default="https://github.com/tile-ai/TileOPs")
    args = parser.parse_args()

    nightly_dir = Path(args.nightly_dir)
    html = build_index(nightly_dir, args.repo_url)
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(html)
    print(f"Index written: {args.output} ({len(list(nightly_dir.iterdir()))} entries scanned)")


if __name__ == "__main__":
    main()
